# src/utils/features_civil.py

# Columnas de materias exactamente como vienen en el CSV de Ingeniería Civil
MATERIAS_EN_ORDEN_CIVIL = [
    "ADMINISTRACION Y MERCADOTECNIA",
    "CIRCUITOS ELECTRICOS",
    "COMPUTACION I",
    "COMPUTACION II",
    "CALCULO I",
    "CALCULO II",
    "CALCULO III",
    "CALCULO IV",
    "CALCULO V",
    "CALCULO VI",
    "DISENO ASISTIDO POR COMPUTADORA I",
    "DISENO ASISTIDO POR COMPUTADORA II",
    "DISENO TECNICO",
    "ESTRUCTURAS I",
    "ESTRUCTURAS II",
    "ESTRUCTURAS III",
    "EVENTOS Y DEPORTES I",
    "EVENTOS Y DEPORTES II",
    "EVENTOS Y DEPORTES III",
    "EVENTOS Y DEPORTES IV",
    "EVENTOS Y DEPORTES V",
    "EVENTOS Y DEPORTES VI",
    "EXPRESION ORAL Y ESCRITA",
    "FISICA I",
    "FISICA II",
    "FISICA III",
    "FISICA IV",
    "FISICA V",
    "FISICA VI",
    "GEOMETRIA ANALITICA",
    "GEOTECNIA I",
    "GEOTECNIA II",
    "HIDRAULICA I",
    "HIDRAULICA II",
    "HORMIGON ARMADO I",
    "IDIOMAS  I",  # doble espacio según encabezado original
    "INGLES I",
    "INGLES II",
    "INGLES III",
    "LABORATORIO DE IDIOMAS I",
    "MATERIALES DE OBRAS CIVILES",
    "MECANICA DE MATERIALES I",
    "MECANICA DE MATERIALES II",
    "MECANICA VECTORIAL I",
    "MECANICA VECTORIAL II",
    "METODOLOGIA DE LA INVESTIGACION I",
    "METODOLOGIA DE LA INVESTIGACION II",
    "PROBABILIDAD Y ESTADISTICA",
    "QUIMICA",
    "TECNOLOGIA DEL HORMIGON",
    "TOPOGRAFIA",
    "VIAS DE COMUNICACION I",
    "VIAS DE COMUNICACION II",
    "ALGEBRA LINEAL I",
    "ALGEBRA LINEAL II",
    "ETICA PROFESIONAL",
]


# Opcional: orden de features para el modelo de predicción de Civil
# Ajusta estos nombres a los atributos reales que tengas en tu modelo .joblib
FEATURES_EN_ORDEN_CIVIL = [
    "Sexo",
    "Estado_Carrera",
    "TiempoEstudio",
    "Ausencias",
    "CincoF",
    "aplazos",
    "Promedio",
    # A partir de aquí, los atributos de materias (en snake_case)
    "admin_mercadotecnia",
    "circuitos_electricos",
    "computacion_i",
    "computacion_ii",
    "calculo_i",
    "calculo_ii",
    "calculo_iii",
    "calculo_iv",
    "calculo_v",
    "calculo_vi",
    "diseno_asistido_pc_i",
    "diseno_asistido_pc_ii",
    "diseno_tecnico",
    "estructuras_i",
    "estructuras_ii",
    "estructuras_iii",
    "eventos_deportes_i",
    "eventos_deportes_ii",
    "eventos_deportes_iii",
    "eventos_deportes_iv",
    "eventos_deportes_v",
    "eventos_deportes_vi",
    "expresion_oral",
    "fisica_i",
    "fisica_ii",
    "fisica_iii",
    "fisica_iv",
    "fisica_v",
    "fisica_vi",
    "geometria_analitica",
    "geotecnia_i",
    "geotecnia_ii",
    "hidraulica_i",
    "hidraulica_ii",
    "hormigon_armado_i",
    "idiomas_i",
    "ingles_i",
    "ingles_ii",
    "ingles_iii",
    "laboratorio_idiomas_i",
    "materiales_obras_civiles",
    "mecanica_materiales_i",
    "mecanica_materiales_ii",
    "mecanica_vectorial_i",
    "mecanica_vectorial_ii",
    "metodologia_investigacion_i",
    "metodologia_investigacion_ii",
    "probabilidad_estadistica",
    "quimica",
    "tecnologia_hormigon",
    "topografia",
    "vias_comunicacion_i",
    "vias_comunicacion_ii",
    "algebra_lineal_i",
    "algebra_lineal_ii",
    "etica_profesional",
]
