# src/utils/features_electricidad.py

MATERIAS_EN_ORDEN_ELECTRICIDAD = [
    "ADMINISTRACION Y MERCADOTECNIA",
    "ALGEBRA  II",
    "ALGEBRA I",
    "AUTOMATIZACION INDUSTRIAL",
    "CIRCUITOS ELECTRICOS I",
    "CIRCUITOS ELECTRICOS II",
    "COMPUTACION II",
    "COMPUTACION I",
    "CONVERSION DE ENERGIA ELECTRICA  II",
    "CONVERSION DE ENERGIA ELECTRICA I",
    "CALCULO I",
    "CALCULO II",
    "CALCULO III",
    "CALCULO IV",
    "CALCULO V",
    "DISENO ASISTIDO POR COMPUTADORA",
    "DISENO TECNICO",
    "ELECTROTECNIA I",
    "ELECTROTECNIA II",
    "ELECTRONICA DE POTENCIA  II",
    "ELECTRONICA DE POTENCIA I",
    "ELECTRONICA DIGITAL I",
    "ELECTRONICA DIGITAL II",
    "ELECTRONICA I",
    "ELECTRONICA II",
    "EMPRENDEDORISMO",
    "EVENTOS Y DEPORTES  II",
    "EVENTOS Y DEPORTES I",
    "EVENTOS Y DEPORTES III",
    "EVENTOS Y DEPORTES IV",
    "EVENTOS Y DEPORTES V",
    "EVENTOS Y DEPORTES VI",
    "EXPRESION ORAL Y ESCRITA",
    "FISICA II",
    "FISICA IV",
    "FUNDAMENTOS DE CONTROL AUTOMATIZADO I",
    "FUNDAMENTOS DE CONTROL AUTOMATIZADO II",
    "FISICA  V",
    "FISICA I",
    "FISICA III",
    "FISICA VI",
    "GEOMETRIA ANALITICA",
    "IDIOMAS I",
    "INGLES I",
    "INGLES II",
    "INGLES III",
    "INSTALACIONES ELECTRICAS I",
    "INSTALACIONES ELECTRICAS II",
    "INSTALACIONES ELECTRICAS III",
    "LABORATORIO DE IDIOMAS I",
    "MEDICION E INSTRUMENTACION",
    "METODOLOGIA DE LA INVESTIGACION I",
    "PROBABILIDADES Y ESTADISTICAS",
    "PROGRAMACION EN LENGUAJES DE COMPUTADORA",
    "QUIMICA",
    "SEGURIDAD E HIGIENE LABORAL",
    "ETICA PROFESIONAL",
]

FEATURES_EN_ORDEN_ELECTRICIDAD = [
    "Sexo", "Estado_Carrera", "TiempoEstudio", "Ausencias",
    "CincoF", "aplazos", "Promedio",
    "admin_mercadotecnia",
    "algebra_ii",
    "algebra_i",
    "automatizacion_industrial",
    "circuitos_electricos_i",
    "circuitos_electricos_ii",
    "computacion_ii",
    "computacion_i",
    "conversion_energia_ii",
    "conversion_energia_i",
    "calculo_i",
    "calculo_ii",
    "calculo_iii",
    "calculo_iv",
    "calculo_v",
    "diseno_asistido_pc",
    "diseno_tecnico",
    "electrotecnia_i",
    "electrotecnia_ii",
    "electronica_potencia_ii",
    "electronica_potencia_i",
    "electronica_digital_i",
    "electronica_digital_ii",
    "electronica_i",
    "electronica_ii",
    "emprendedorismo",
    "eventos_deportes_ii",
    "eventos_deportes_i",
    "eventos_deportes_iii",
    "eventos_deportes_iv",
    "eventos_deportes_v",
    "eventos_deportes_vi",
    "expresion_oral",
    "fisica_ii",
    "fisica_iv",
    "fund_control_auto_i",
    "fund_control_auto_ii",
    "fisica_v",
    "fisica_i",
    "fisica_iii",
    "fisica_vi",
    "geometria_analitica",
    "idiomas_i",
    "ingles_i",
    "ingles_ii",
    "ingles_iii",
    "instalaciones_electricas_i",
    "instalaciones_electricas_ii",
    "instalaciones_electricas_iii",
    "laboratorio_idiomas_i",
    "medicion_instrumentacion",
    "metodologia_investigacion_i",
    "probabilidades_estadisticas",
    "programacion_lenguajes_computadora",
    "quimica",
    "seguridad_higiene_laboral",
    "etica_profesional",
]
